### ISSUE TITLE
impliment Flyto 

### ISSUE THREAD

**Issue by dacresni** [OpenSTL/VacantSearch#21]
take coordinates from results JSON and put into flyTo map function that activates from onclick event when list element is clicked on.

**Comment by mrao2** [comment]
priority: HIGH

**Comment by dacresni** [comment]
I broke the rules and committed to master  [diff](https://github.com/OpenDataSTL/VacantSearch/commit/6ee28d638869493ca369def6336249e5463fb008?diff=unified)
